DISPLAY_MODE_POINTS = "Points only"
DISPLAY_MODE_LINES = "Lines only"
DISPLAY_MODE_LINES_POINTS = "Lines + points"
DISPLAY_MODES = (DISPLAY_MODE_POINTS, DISPLAY_MODE_LINES, DISPLAY_MODE_LINES_POINTS)
DEFAULT_DISPLAY_MODE = DISPLAY_MODE_LINES
DEFAULT_USE_DENSITY = True
